name: 'vpc_destroy'
on:
  workflow_dispatch:
    
# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
  run:
    shell: bash
env:
  TF_STATE_BUCKET: mm-labs-aws-tf-statebucket-dev
  TF_STATELOCK_TABLE : mm-labs-aws-tf-statelock
  REGION: us-east-1
  ENV: dev
  
jobs:  
  terraform-plan:
    name: 'terraform-destroy'
    environment: dev
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2       

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.5

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.MM_SECRET_KEY_ID }}
        aws-region: ${{ env.REGION }}
        
    - name: Terraform Init
      run: terraform init -no-color -reconfigure -force-copy -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="key=${{ env.TF_VAR_STATE_FILE }}" -backend-config="dynamodb_table=$TF_STATELOCK_TABLE" -backend-config="encrypt=true"
      env:
        TF_VAR_STATE_FILE: "$ENV-${{ github.event.repository.name }}.tfstate"
      
    - name: Terraform Destroy   
      run: terraform destroy -auto-approve -var-file="$ENV/terraform.tfvars" -input=false
